---
- name: Enable pacman options
  become: true
  ansible.builtin.replace:
    backup: true
    path: /etc/pacman.conf
    regexp: '#\s*({{ item }}.*)'
    replace: '\1'
  loop:
    - VerbosePkgLists  # show from->to version and download/upgrade sizes
    - ParallelDownloads  # download more pkgs at concurrently

- name: Update Arch Linux keyring
  become: true
  ansible.builtin.package:
    name: archlinux-keyring
    state: present

- name: Check system update status and perform if needed
  block:
    - name: Check the timestamp of the last pacman sync
      become: true
      ansible.builtin.stat:
        path: /var/lib/pacman/sync/core.db
      register: baseline_pacman_sync_db_stat

    - name: Set update needed flag
      ansible.builtin.set_fact:
        baseline_update_needed: "{{ not baseline_pacman_sync_db_stat.stat.exists or (ansible_facts.date_time.epoch | int - baseline_pacman_sync_db_stat.stat.mtime | int > 3600) }}"
      when: not baseline_pacman_sync_db_stat.stat.exists or (ansible_facts.date_time.epoch | int - baseline_pacman_sync_db_stat.stat.mtime | int > 3600)

    - name: Set update not needed flag
      ansible.builtin.set_fact:
        baseline_update_needed: false
      when: baseline_pacman_sync_db_stat.stat.exists and (ansible_facts.date_time.epoch | int - baseline_pacman_sync_db_stat.stat.mtime | int <= 3600)

    - name: Debug update status
      ansible.builtin.debug:
        msg: "System update {{ 'needed' if baseline_update_needed else 'not needed' }} (last sync: {{ baseline_pacman_sync_db_stat.stat.mtime | default('never') }})"

    - name: Upgrade system
      become: true
      ansible.builtin.package:
        update_cache: true
        upgrade: true
      when: baseline_update_needed

    - name: Reboot the VM
      become: true
      ansible.builtin.reboot:
        reboot_timeout: 600
        connect_timeout: 60
        post_reboot_delay: 15
        test_command: uptime
      when: baseline_update_needed

- name: Install baseline pkgs
  become: true
  ansible.builtin.package:
    name:
      - xdg-user-dirs  # common user dirs
      - xorg-xinit  # start GUI
      - xorg-server  # Xorg server
      - xorg-apps  # Xorg apps
      - picom  # xorg compositor
      - xterm  # default terminal
      - ttf-bitstream-vera  # serif and mono
      - ttf-dejavu  # Bitstream Vera modified w/more Unicode
      - ttf-croscore  # Helvetica, Times, and Courier
      - xss-lock  # xorg locker
      - polkit  # privs management
      - dmidecode  # used for checking for virtualization
      - firefox  # web browser
      - chromium  # web browser
      - gedit  # text editor
      - flameshot  # screenshot
      - pkgfile  # pkg search from repos
      - strace  # debugger
      - bind-tools  # domain resolving
      - udisks2  # disk mounting
      - arandr  # desktop display configurator
      - base-devel  # meta package for compiling (e.g. AUR)
      - git  # repos
      - python  # Python3
      - python-pip  # pip package installer
      - python-setuptools  # Python3 setuptools
      - numlockx  # numlock on at login
      - ghostwriter  # Markdown editor
      - hunspell-en_us  # English spellcheck (for ghostwriter)
      # - libreoffice-still  # office suite of programs
      - pulseaudio  # PulseAudio
      - pavucontrol  # PulseAudio GUI for volume
      - vlc  # multimedia player
      - packer  # automate VM building
      - man-db  # manpages program
      - man-pages  # actual manpages
      - blueman  # Bluetooth
      - dialog  # for wifi-menu
      - netctl  # dep for wifi-menu
      - pcmanfm  # file explorer GUI
      - gvfs  # dep for pcmanfm features
      - unzip  # zip
      - evince  # PDF viewer
      - reflector  # update pacman mirrors
      - bluez  # bluetooth
      - bluez-utils  # bluetooth utils
      - pulseaudio-bluetooth  # pulseaudio dep for bluetooth
      - xf86-input-synaptics  # touchpad
      - android-file-transfer  # access files from Android device
      - spotify-launcher  # Spotify music
      - linux-headers  # Linux kernel headers
    state: present

- name: Enable baseline services
  become: true
  ansible.builtin.service:
    name: '{{ item }}'
    enabled: true
    state: started
  loop:
    - bluetooth
    - pkgfile-update

- name: Disable bluetooth on boot
  become: true
  vars:
    bluetooth_enabled: 'false'
  ansible.builtin.lineinfile:
    backup: true
    backrefs: true
    path: /etc/bluetooth/main.conf
    regexp: '^#\s*(AutoEnable)=.*$'
    line: '\1={{ bluetooth_enabled }}'
    state: present

- name: Set default systemd service timeout
  become: true
  ansible.builtin.blockinfile:
    path: /etc/systemd/system.conf
    marker: "# {mark} systemd_timeout"
    create: true
    state: present
    mode: '0644'
    block: |
      DefaultTimeoutStopSec=15s

# Only works for first time Chromium is opened and creates its profile
# - name: Set Chromium to use GTK theme
#   ignore_errors: true
#   ansible.builtin.lineinfile:
#     backup: true
#     backrefs: true
#     path: ~/.config/chromium/Default/Preferences
#     regexp: '(.*)"system_theme":0(.*)'
#     line: '\1 "system_theme":1 \2'
#     state: present

# https://wiki.archlinux.org/title/Touchpad_Synaptics#Frequently_used_options
- name: Configure touchpad to use sane defaults
  become: true
  ansible.builtin.copy:
    remote_src: false
    src: files/70-synaptics.conf
    dest: /etc/X11/xorg.conf.d/
    mode: '0644'
    owner: root
    group: root

- name: Change default sudo prompt timeout
  become: true
  ansible.builtin.lineinfile:
    path: /etc/sudoers.d/sudo_prompt_timeout
    line: Defaults timestamp_timeout=15
    create: true
    validate: 'visudo --check --strict --file=%s'
    mode: '0440'
    owner: root
    group: root
    state: present
