---
passwordless_sudo_user: '{{ ansible_user }}'
passwordless_sudo_file: /etc/sudoers
passwordless_sudo_program: /usr/bin/pacman
# aur_packages:
#   - package1
#   - package2
#   - package3
aur_packages_state: present
