---
- name: Prepare and configure all hosts
  hosts: all
  roles:
    - baseline
    - arch_recommendations
    - ufw_firewall
    - dns_blackhole
    - i3
    - shell
    - theme
    - conky
    - nitrogen
    - keepassxc
    - powertop
    - locale
    - docker
    - grub
    - calibre
    - virtualization
    - vagrant
    # NOTE: steam must be at the end since it upgrades the system,
    # which breaks some other things until a reboot is completed
    - steam
