---
# Install Vagrant (VM manager)
#
# Reference:
# https://wiki.archlinux.org/title/Vagrant#Installation
- name: Install vagrant from AUR
  vars:
    function_yay_aur_packages:
      - vagrant
    function_yay_aur_packages_state: present
  ansible.builtin.import_role:
    name: function_yay

- name: Install needed OS pkgs
  become: true
  ansible.builtin.package:
    name:
      - python-paramiko
      - libvirt
      - qemu
      - virt-manager
      - nfs-utils
      - dnsmasq
      - dmidecode
    state: present

- name: Add '{{ ansible_user }}' to libvirt group
  become: true
  ansible.builtin.user:
    name: '{{ ansible_user }}'
    groups: libvirt
    append: true
    state: present

- name: Enable and start the libvirtd socket
  become: true
  ansible.builtin.systemd:
    name: libvirtd.socket
    state: started
    enabled: true

# https://wiki.archlinux.org/title/Vagrant#Mounting_NFS_shared_folders:_mount.nfs:_requested_NFS_version_or_transport_protocol_is_not_supported
- name: '`nfs.conf` enable vers3'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nfs.conf
    regexp: '^#\s*vers3.*$'
    line: vers3=y
    state: present

- name: '`nfs.conf` enable UDP'
  become: true
  ansible.builtin.lineinfile:
    path: /etc/nfs.conf
    regexp: '^#\s*udp=.*$'
    line: udp=y
    state: present

# https://wiki.archlinux.org/title/Vagrant#Mounting_NFS_shared_folders:_mount.nfs:_requested_NFS_version_or_transport_protocol_is_not_supported
- name: Enable and start nfs-server service
  become: true
  ansible.builtin.systemd:
    name: nfs-server
    state: started
    enabled: true

- name: Check for already installed Vagrant plugins
  ansible.builtin.command: vagrant plugin list
  register: vagrant_installed_plugins
  changed_when: false
  failed_when: false

- name: Ensure required Vagrant plugins are installed
  ansible.builtin.command: vagrant plugin install {{ item }}
  loop:
    - vagrant-libvirt
    - vagrant-dns
    - vagrant-scp
  when: item not in vagrant_installed_plugins.stdout
  loop_control:
    label: "{{ item }}"
  changed_when: true
