Vagrant.configure("2") do |config|
  config.vm.define "manjaro"
  config.vm.hostname = "manjaro"

  config.vm.box = "Zelec/manjarolinux"
  # config.vm.box = "archlinux/archlinux"
  config.vm.box_check_update = true
  
  # config.vm.network :bridged, :bridge => "enp3s0"
  config.vm.network "forwarded_port", guest: 22, host: 2222
  
  config.vm.provider "libvirt" do |vb|
    vb.memory = "8192"
  end

  config.vm.provision "shell", inline: <<-SHELL
    sed -i 's/.*nameserver.*/nameserver 8.8.8.8/' /etc/resolv.conf
    pacman-mirrors --country United_States
    pacman -S --refresh --refresh --sysupgrade --noconfirm vim net-tools
    echo 'DONE!'
  SHELL
end
