Vagrant.configure("2") do |config|
  config.vm.define "manjaro"
  config.vm.hostname = "manjaro"

  config.vm.box = "Zelec/manjarolinux"
  config.vm.box_check_update = true

  config.vm.network "forwarded_port", guest: 22, host: 2222
  config.vm.provider "libvirt" do |vb|
    vb.memory = "8192"
  end

  config.vm.provision "shell", inline: <<-SHELL
    pacman-mirrors --country United_States
    pacman -Syyu --noconfirm vim net-tools
    echo 'DONE!'
  SHELL
end
