---
- name: Ensure certain baseline packages are remove and present
  hosts: all
  tasks:

  - name: Remove packages
    become: true
    community.general.pacman:
      name:
        - palemoon-bin
      state: absent

  - name: Remove unneeded files/dirs
    ansible.builtin.file:
      path: '{{ item }}'
      state: absent
    loop:
      - ~/.moonchild productions

  - name: Install packages
    become: true
    community.general.pacman:
      name:
        - firefox
        - steam
        - pkgfile
        - virt-manager
        - qemu
        - vde2
        - ebtables
        - dnsmasq
        - bridge-utils
        - openbsd-netcat
        - redshift
        - calibre
        - docker
        - lynx
        - strace
        - bind-tools
        - gedit
        - udisks2
        - neovim
        - zsh
      state: present

  - name: Change default shell to zsh
    become: true
    user:
      name: '{{ ansible_user_id }}'
      shell: /bin/zsh
