# Molecule docs:
# - https://molecule.readthedocs.io/en/latest/examples.html
# Vagrant:
# - https://github.com/ansible-community/molecule-vagrant/blob/main/README.rst
---
dependency:
  name: galaxy
driver:
  name: vagrant
  # https://molecule.readthedocs.io/en/latest/examples.html#parallel-usage-example
  parallel: true  # currently only available for use with the Docker driver.
  provision: true
  provider:
    name: virtualbox
platforms:
  - name: arch-instance
    box: 'archlinux/archlinux'
    cpus: 2
    memory: 4096
    config_options:
      ssh.remote_user: 'vagrant'
      ssh.keep_alive: true
    instance_raw_config_args:  # REQUIRES: driver -> provision: true
      # https://developer.hashicorp.com/vagrant/docs/provisioning/shell
      # NOTE: because Arch Linux is a rolling distro, package versions can
      # quickly go out-of-date. This performs a full system upgrade and reboots,
      # which is necessary if the kernel versions differ. This can impact future
      # package installations in weird ways such as mismatched versions for
      # kernel modules (e.g. in the case of iptables/ufw, when first installed).
      # - 'vm.provision :shell, reboot: "true", inline:
      - 'vm.provision :shell, inline:
          "
            pacman \
              -S \
              --refresh \
              --refresh \
              --sysupgrade \
              --noconfirm \
                python
          "
        '
  - name: kali-instance
    box: 'kalilinux/rolling'
    cpus: 2
    memory: 4096
    config_options:
      ssh.remote_user: 'vagrant'
      ssh.keep_alive: true
    provider_raw_config_args:
      - 'gui = false'  # prevent VM GUI from displaying
    instance_raw_config_args:  # REQUIRES: driver -> provision: true
      # https://developer.hashicorp.com/vagrant/docs/provisioning/shell
      - 'vm.provision :shell, inline:
          "
            apt
              install \
                --yes
                  python3
          "
        '
provisioner:
  name: ansible
  env:
    # https://www.jeffgeerling.com/blog/2020/getting-colorized-output-molecule-and-ansible-on-github-actions-ci
    PY_COLORS: '1'
    ANSIBLE_FORCE_COLOR: '1'
    ANSIBLE_PYTHON_INTERPRETER: '/usr/bin/python3'
    ANSIBLE_LOG_PATH: '/tmp/ansible.molecule.log'
  config_options:
    defaults:
      # Not used but prevents vault descryption errors
      vault_password_file: "${MOLECULE_PROJECT_DIRECTORY}/.vault_pass"
      stdout_callback: debug
      stderr_callback: debug
  playbooks:
    prepare: prepare.yml
verifier:
  name: ansible
# lint: |
#   ansible-lint
