---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: archlinux
    pre_build_image: false
    dockerfile: archlinux.dockerfile
provisioner:
  name: ansible
verifier:
  name: ansible
