---
- name: Pre-Converge Actions
  hosts: all
  tasks:

    - name: Target OS
      ansible.builtin.debug:
        msg:
          - 'TARGET OS: {{ ansible_facts["distribution"] }}'
          - 'OS FAMILY: {{ ansible_facts["os_family"] }}'

    - name: === ARCH BLOCK ===
      when: ansible_facts['distribution'] == "Archlinux"
      block:

        - name: '[Arch] Full system upgrade'
          become: true
          community.general.pacman:
            update_cache: true
            upgrade: true
          notify: 'Reboot'

        - name: '[Arch] Install necessary packages'
          become: true
          community.general.pacman:
            name:
              - archlinux-keyring
              - base
              - base-devel
              - python
            state: latest
          notify: 'Reboot'

  #    - name: === KALI BLOCK ===
  #      when: ansible_facts['distribution'] == "Kali"
  #      block:
  #
  #        - name: '[Kali] Update apt cache'
  #          become: true
  #          # apt cache update not necessary but desired,
  #          # prevents some rolling distro-related errors
  #          ignore_errors: true
  #          ansible.builtin.apt:
  #            update_cache: true
  #            cache_valid_time: 3600

  handlers:
    - name: 'Reboot'
      become: true
      ansible.builtin.reboot:
