#!/usr/bin/env ansible-playbook
#
# This playbook will ensure yay and the Ansible module ansible-yay is installed
# on the local machine (Ansible controller).
---
- name: Install yay and dependencies
  hosts: all
  tasks:
  - name: Install yay and dependencies
    become: true
    delegate_to: 127.0.0.1
    ansible.builtin.package:
      name:
        - base-devel
        - git
        - yay
      state: present
  - name: Make folder for git clone
    delegate_to: 127.0.0.1
    ansible.builtin.file:
      path: /tmp/ansible-yay
      state: directory
  - name: Clone ansible-yay (Ansible) module
    delegate_to: 127.0.0.1
    ansible.builtin.git:
      repo: 'https://github.com/mnussbaum/ansible-yay.git'
      dest: /tmp/ansible-yay
      clone: true
  - name: Ensure Ansible module dir exists
    delegate_to: 127.0.0.1
    ansible.builtin.file:
      # https://docs.ansible.com/ansible/latest/dev_guide/developing_locally.html#id2
      path: ~/.ansible/plugins/modules/
      state: directory
  - name: Copy yay module to Ansible module folder
    delegate_to: 127.0.0.1
    ansible.builtin.copy:
      remote_src: true
      src: /tmp/ansible-yay/yay
      dest: ~/.ansible/plugins/modules/
      mode: '0555'
