#!/usr/bin/env ansible-playbook
#
# Add/remove temporary user when using yay module since
# yay cannot be ran as sudo but will require (and prompt for
# sudoer password) later
# Reference:
# https://github.com/kewlfft/ansible-aur#create-the-aur_builder-user
---
- name: Add/Remove yay passwordless sudo user (to install AUR packages)
  hosts: all
  vars:
  - install_passwordless_sudo_user: true
  - passwordless_sudo_user: aur_builder
  - passwordless_sudo_file: /etc/sudoers.d/11-install-{{ passwordless_sudo_user }}
  tasks:

  # --- INSTALL USER ---
  - name: Create the `{{ passwordless_sudo_user }}` user
    become: true
    when: install_passwordless_sudo_user is defined and
      install_passwordless_sudo_user is true
    ansible.builtin.user:
      name: '{{ passwordless_sudo_user }}'
      create_home: false
      group: wheel
      state: present

  - name: Allow the `{{ passwordless_sudo_user }}` user to run `sudo pacman`
      without a password
    become: true
    when: install_passwordless_sudo_user is defined and
      install_passwordless_sudo_user is true
    ansible.builtin.lineinfile:
      path: '{{ passwordless_sudo_file }}'
      line: '{{ passwordless_sudo_user }} ALL=(ALL) NOPASSWD: /usr/bin/pacman'
      create: true
      validate: 'visudo -cf %s'
      state: present

  # --- UNINSTALL USER ---
  - name: Remove the `{{ passwordless_sudo_user }}` user
    become: true
    when: install_passwordless_sudo_user is defined and
      install_passwordless_sudo_user is false
    ansible.builtin.user:
      name: '{{ passwordless_sudo_user }}'
      remove: true
      state: absent

  - name: Remove the `{{ passwordless_sudo_file }}` file
    become: true
    when: install_passwordless_sudo_user is defined and
      install_passwordless_sudo_user is false
    ansible.builtin.file:
      path: '{{ passwordless_sudo_file }}'
      state: absent
