#!/usr/bin/env ansible-playbook
#
# Baseline packages and simple configurations
---
- name: Install (and remove) baseline packages from pacman, AUR, and PyPI
  hosts: all
  tasks:

  - name: Remove unwanted pkgs
    become: true
    community.general.pacman:
      name: '{{ item }}'
      state: absent
    loop:
      - palemoon-bin

  - name: Remove unneeded files/dirs
    ansible.builtin.file:
      path: '{{ item }}'
      state: absent
    loop:
      - ~/.moonchild productions

  - name: Install pacman pkgs
    become: true
    community.general.pacman:
      # installation takes while so method will show "progress"
      name: '{{ item }}'
      update_cache: true
      state: present
    loop:
      - firefox  # web browser
      - chromium  # web browser
      - gedit  # text editor
      - flameshot  # screenshot
      - pkgfile  # pkg search from repos
      - strace  # debugger
      - bind-tools  # domain resolving
      - udisks2  # disk mounting
      - arandr  # desktop display configurator
      - base-devel  # meta package for compiling (e.g. AUR)
      - git  # repos
      - yay  # AUR installation
      - python  # Python3
      - python-pip  # pip package installer
      - numlockx  # numlock on at login
      - marker  # Markdown editor
      - libreoffice  # office suite of programs
      - pulseaudio  # Pulse Audio
      - pavucontrol  # PulseAudio GUI for volume
      - pa-applet  # PulseAudio statusbar applet
      - packer  # automate VM building

- name: Install AUR pkgs
  vars:
    aur_packages:
      - librewolf-bin  # security-focused web browser
      - optimus-manager  # GPU switcher
  ansible.builtin.import_playbook: function_yay.yml

- hosts: all
  tasks:

    - name: Miscellaneous config steps (that don't need their own playbooks)
      block:

        - name: Enable optimus-manager service
          become: true
          ansible.builtin.service:
            name: optimus-manager
            enabled: true
            state: started

        - name: Disable lightdm greeter GUI login (when using optimus to switch GPUs)
          become: true
          ansible.builtin.replace:
            backup: true
            path: /etc/lightdm/lightdm.conf
            regexp: '^\s*(greeter-session=.*)'
            replace: '#\1'
            validate: 'lightdm --show-config --config=%s'

        - name: Tweak blur lock screen to blur more
          become: true
          ansible.builtin.lineinfile:
            backup: true
            backrefs: true
            path: /usr/bin/blurlock
            regexp: '(.*) -blur [0-9.]+x[0-9.]+ (.*)'
            line: '\1 -blur 0x100 \2'
            state: present

        - name: Disable default i3 help display in Conky
          become: true
          ansible.builtin.replace:
            backup: true
            path: /usr/bin/start_conky_maia
            regexp: '(.*/usr/share/conky/conky1.10_shortcuts_maia.*)'
            replace: '#\1'
