#!/usr/bin/env ansible-playbook
#
# Barebones setup to make a fresh Arch Linux usable
---
- name: Install baseline pkgs
  hosts: all
  tasks:

    - name: Enable pacman options
      become: true
      ansible.builtin.replace:
        backup: true
        path: /etc/pacman.conf
        regexp: '#\s*({{ item }}.*)'
        replace: '\1'
      loop:
        - VerbosePkgLists  # show from->to version and download/upgrade sizes
        - ParallelDownloads  # download more pkgs at concurrently

    - name: Update keyring
      become: true
      community.general.pacman:
        name: archlinux-keyring
        state: latest

    - name: Gather the package facts
      ansible.builtin.package_facts:
        manager: auto

    - name: Avoid pkg conflict ('acpilight' overwrites *xbacklight* from 'xorg')
      become: true
      ansible.builtin.package:
        name: xorg  # desktop GUI
        state: present
      when: "'acpilight' not in ansible_facts.packages"

    - name: Install pacman pkgs
      become: true
      community.general.pacman:
        name:
          - xdg-user-dirs  # common user dirs
          - xorg-xinit  # start GUI
          - picom  # xorg compositor
          - xterm  # default terminal
          - ttf-bitstream-vera  # serif and mono
          - ttf-dejavu  # Bitstream Vera modified w/more Unicode
          - ttf-croscore  # Helvetica, Times, and Courier
          - grub-customizer  # GUI for GRUB menu
          - xorg-xhost  # hard dep for grub-customizer
          - xautolock  # xorg locker
          - polkit  # privs management
          - dmidecode  # used for checking for virtualization
          - firefox  # web browser
          - chromium  # web browser
          - gedit  # text editor
          - flameshot  # screenshot
          - pkgfile  # pkg search from repos
          - strace  # debugger
          - bind-tools  # domain resolving
          - udisks2  # disk mounting
          - arandr  # desktop display configurator
          - base-devel  # meta package for compiling (e.g. AUR)
          - git  # repos
          - python  # Python3
          - python-pip  # pip package installer
          - python-setuptools  # Python3 setuptools
          - numlockx  # numlock on at login
          - ghostwriter  # Markdown editor
          - libreoffice  # office suite of programs
          - pulseaudio  # PulseAudio
          - pavucontrol  # PulseAudio GUI for volume
          - packer  # automate VM building
          - man-db  # manpages program
          - man-pages  # actual manpages
          - blueman  # Bluetooth
          - dialog  # for wifi-menu
          - netctl  # dep for wifi-menu
          - pcmanfm  # file explorer GUI
          - gvfs  # dep for pcmanfm features
          - unzip  # zip
          - evince  # PDF viewer
          - reflector  # update pacman mirrors
          - bluez  # bluetooth
          - bluez-utils  # bluetooth utils
          - pulseaudio-bluetooth  # pulseaudio dep for bluetooth
          - xf86-input-synaptics  # touchpad
          - android-file-transfer  # access files from Android device
        state: present

    - name: Enable services
      become: true
      ansible.builtin.service:
        name: '{{ item }}'
        enabled: true
        state: started
      loop:
        - bluetooth

    - name: Disable bluetooth on boot
      become: true
      vars:
        bluetooth_enabled: 'false'
      ansible.builtin.lineinfile:
        backup: true
        backrefs: true
        path: /etc/bluetooth/main.conf
        regexp: '^#\s*(AutoEnable)=.*$'
        line: '\1={{ bluetooth_enabled }}'
        state: present

    - name: Set default systemd service timeout
      become: true
      ansible.builtin.blockinfile:
        path: /etc/systemd/system.conf
        marker: "# {mark} systemd_timeout"
        create: true
        state: present
        mode: '0644'
        block: |
          DefaultTimeoutStopSec=15s

    - name: Set Chromium to use GTK theme
      ignore_errors: true
      ansible.builtin.lineinfile:
        backup: true
        backrefs: true
        path: ~/.config/chromium/Default/Preferences
        regexp: '(.*)"system_theme":0(.*)'
        line: '\1 "system_theme":1 \2'
        state: present

    # https://wiki.archlinux.org/title/Touchpad_Synaptics#Frequently_used_options
    - name: Configure touchpad to use sane defaults
      become: true
      ansible.builtin.copy:
        remote_src: false
        src: files/70-synaptics.conf
        dest: /etc/X11/xorg.conf.d/
        mode: '0644'
        owner: root
        group: root

    - name: Change default sudo prompt timeout
      become: true
      ansible.builtin.lineinfile:
        path: /etc/sudoers.d/sudo_prompt_timeout
        line: Defaults timestamp_timeout=15
        create: true
        validate: 'visudo -csf %s'
        mode: '0440'
        owner: root
        group: root
        state: present
