#!/usr/bin/env ansible-playbook
#
# Barebones setup to make a fresh Arch Linux usable
---
- name: Install baseline pkgs
  hosts: all
  tasks:

    - name: Enable pacman options
      become: true
      ansible.builtin.replace:
        backup: true
        path: /etc/pacman.conf
        regexp: '#\s*({{ item }}.*)'
        replace: '\1'
      loop:
        - VerbosePkgLists  # show from->to version and download/upgrade sizes
        - ParallelDownloads  # download more pkgs at concurrently

    - name: Upgrade system
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install pacman pkgs
      become: true
      ansible.builtin.pacman:
        name:
          - xdg-user-dirs  # common user dirs
          - xorg  # GUI
          - xorg-xinit  # start GUI
          - picom  # xorg compositor
          - lightdm  # display manager
          - lightdm-gtk-greeter  # lightdm greeter GUI
          - i3-gaps  # tiling window manager
          - i3blocks  # feed generator for status bar
          - i3lock  # screenlocker
          - i3status  # i3 status bar
          - xterm  # default terminal
          - ttf-bitstream-vera  # serif and mono
          - ttf-dejavu  # Bitstream Vera modified w/more Unicode
          - ttf-croscore  # Helvetica, Times, and Courier
          - grub-customizer  # GUI for GRUB menu
          - xorg-xhost  # hard dep for grub-customizer
          - polkit  # hard dep for grub-customizer
          - dmidecode  # used for checking for virtualization
          - firefox  # web browser
          - chromium  # web browser
          - gedit  # text editor
          - flameshot  # screenshot
          - pkgfile  # pkg search from repos
          - strace  # debugger
          - bind-tools  # domain resolving
          - udisks2  # disk mounting
          - arandr  # desktop display configurator
          - base-devel  # meta package for compiling (e.g. AUR)
          - git  # repos
          - python  # Python3
          - python-pip  # pip package installer
          - numlockx  # numlock on at login
          - marker  # Markdown editor
          - libreoffice  # office suite of programs
          - pulseaudio  # PulseAudio
          - pavucontrol  # PulseAudio GUI for volume
          - packer  # automate VM building
          - conky  # sysmon
          - man-db  # manpages program
          - man-pages  # actual manpages
          - blueman  # Bluetooth
          - dialog  # for wifi-menu
          - netctl  # dep for wifi-menu
          - pcmanfm  # file explorer GUI
          - gvfs  # dep for pcmanfm features
          - xfce4-power-manager  # power manager applet
          - unzip  # zip
          - evince  # PDF viewer
        state: present

    - name: === LIGHTDM BLOCK ===
      block:

        # https://wiki.archlinux.org/title/LightDM#Enabling_autologin
        - name: Configure lightdm to use i3 by default
          become: true
          ansible.builtin.replace:
            path: /etc/lightdm/lightdm.conf
            regexp: '#user-session=default'
            replace: 'user-session=i3'

        - name: 'Autologin username {{ ansible_user }}'
          become: true
          ansible.builtin.replace:
            path: /etc/lightdm/lightdm.conf
            regexp: '#autologin-user='
            replace: 'autologin-user={{ ansible_user }}'

        - name: Autologin timeout to 0s
          become: true
          ansible.builtin.replace:
            path: /etc/lightdm/lightdm.conf
            regexp: '#autologin-user-timeout=0'
            replace: 'autologin-user-timeout=0'
            validate: 'lightdm --show-config --config=%s'

        - name: Ensure groups exists
          become: true
          ansible.builtin.group:
            name: '{{ item }}'
            system: true
            state: present
          loop:
            - nopasswdlogin
            - autologin

        - name: Ensure user '{{ ansible_user }}' is a member of groups
          become: true
          ansible.builtin.user:
            name: '{{ ansible_user }}'
            groups: '{{ item }}'
            append: true
          loop:
            - nopasswdlogin
            - autologin

        - name: Pam config for passwordless login
          become: true
          ansible.builtin.lineinfile:
            path: /etc/pam.d/lightdm
            line: auth sufficient pam_succeed_if.so user ingroup nopasswdlogin
            state: present

        - name: PAM settings for autologin
          become: true
          ansible.builtin.replace:
            path: /etc/pam.d/lightdm-autologin
            regexp: 'auth.*required pam_succeed_if.so user != root quiet_success'
            replace: ''

        - name: Enable lightdm service
          become: true
          ansible.builtin.service:
            name: lightdm
            state: started
            enabled: true

    - name: === CONKY BLOCK ===
      vars:
        conky_theme_dir: /usr/share/conky/
      block:

        - name: Create conky directory
          become: true
          ansible.builtin.file:
            dest: '{{ conky_theme_dir }}'
            state: directory
            mode: '0755'

        - name: Upload conky theme
          become: true
          ansible.builtin.copy:
            remote_src: false
            src: files/conky_solarized
            dest: '{{ conky_theme_dir }}'
            mode: '0644'

    # https://wiki.archlinux.org/index.php/VirtualBox/Install_Arch_Linux_as_a_guest
    - name: Check for Virtualbox virtualization
      become: true
      changed_when: false
      ignore_errors: true
      ansible.builtin.shell:
        cmd: dmidecode | grep --ignore-case --quiet --extended-regexp 'virtualbox|vbox'
      register: is_virtualbox

    - name: === VIRTUALBOX BLOCK ===
      when: is_virtualbox.rc == 0
      block:

        - name: Install Virtualbox Guest and NFS customizations
          become: true
          ansible.builtin.pacman:
            name:
              - virtualbox-guest-utils
              - nfs-utils
            state: present

        - name: Enable Guest Additions and NFS services
          become: true
          ansible.builtin.service:
            name: '{{ item }}'
            state: started
            enabled: true
          loop:
            - vboxservice
            - rpcbind

        - name: Add `{{ ansible_user }}` to docker group
          become: true
          ansible.builtin.user:
            name: '{{ ansible_user }}'
            groups: vboxsf
            append: true
            state: present

- ansible.builtin.import_playbook: lightdm_dracula_theme.yml

- name: Install AUR pkgs
  vars:
    aur_packages:
      - i3exit  # lock screen blur
      - dmenu2  # keyboard-driven program launcher
      - pa-applet-git  # applet for PulseAudio
      - clipit  # clipboard applet
  ansible.builtin.import_playbook: function_yay.yml

- name: Post-AUR Installs
  hosts: all
  tasks:

    # Requires i3exit to be installed first
    - name: Blurrier blurlock screen (from i3exit)
      become: true
      ansible.builtin.lineinfile:
        backup: true
        backrefs: true
        path: /usr/bin/blurlock
        regexp: '(.*) -blur [0-9.]+x[0-9.]+ (.*)'
        line: '\1 -blur 0x100 \2'
        state: present
