#!/usr/bin/env ansible-playbook
#
# Barebones setup to make a fresh Arch Linux usable
---
- name: Install baseline pkgs
  hosts: all
  tasks:

    - name: Enable pacman options
      become: true
      ansible.builtin.replace:
        backup: true
        path: /etc/pacman.conf
        regexp: '#\s*({{ item }}.*)'
        replace: '\1'
      loop:
        - VerbosePkgLists  # show from->to version and download/upgrade sizes
        - ParallelDownloads  # download more pkgs at concurrently

    - name: Upgrade system
      become: true
      community.general.pacman:
        update_cache: true
        upgrade: true

    - name: Install pacman pkgs
      become: true
      ansible.builtin.pacman:
        name:
          - xdg-user-dirs  # common user dirs
          - xorg  # GUI
          - xorg-xinit  # start GUI
          - picom  # xorg compositor
          - xterm  # default terminal
          - ttf-bitstream-vera  # serif and mono
          - ttf-dejavu  # Bitstream Vera modified w/more Unicode
          - ttf-croscore  # Helvetica, Times, and Courier
          - grub-customizer  # GUI for GRUB menu
          - xorg-xhost  # hard dep for grub-customizer
          - xautolock  # xorg locker
          - polkit  # privs management
          - dmidecode  # used for checking for virtualization
          - firefox  # web browser
          - chromium  # web browser
          - gedit  # text editor
          - flameshot  # screenshot
          - pkgfile  # pkg search from repos
          - strace  # debugger
          - bind-tools  # domain resolving
          - udisks2  # disk mounting
          - arandr  # desktop display configurator
          - base-devel  # meta package for compiling (e.g. AUR)
          - git  # repos
          - python  # Python3
          - python-pip  # pip package installer
          - python-setuptools  # Python3 setuptools
          - numlockx  # numlock on at login
          - marker  # Markdown editor
          - libreoffice  # office suite of programs
          - pulseaudio  # PulseAudio
          - pavucontrol  # PulseAudio GUI for volume
          - packer  # automate VM building
          - man-db  # manpages program
          - man-pages  # actual manpages
          - blueman  # Bluetooth
          - dialog  # for wifi-menu
          - netctl  # dep for wifi-menu
          - pcmanfm  # file explorer GUI
          - gvfs  # dep for pcmanfm features
          - unzip  # zip
          - evince  # PDF viewer
          - ripgrep  # fast, recursive grep searcher
          - fd  # faster `find` command
          - reflector  # update pacman mirrors
        state: present
