#!/usr/bin/env ansible-playbook
#
# Configure host default language to Spanish
#
# Reference:
# - https://serverfault.com/questions/959026/how-do-i-generate-and-set-the-locale-using-ansible#981742
---
- name: Set default language to Spanish
  hosts: all

  vars:
    desired_locale: es_US.UTF-8

  tasks:

    - name: Check original locale
      ansible.builtin.command:
        cmd: localectl status
      register: locale_status
      changed_when: false

    - name: Parse 'LANG' var from current locale
      ansible.builtin.set_fact:
        locale_lang: "{{ locale_status.stdout | regex_search('LANG=([^\n]+)', '\\1') | first }}"

    - name: Display facts
      ansible.builtin.debug:
        msg:
          - 'locale_status: {{ locale_status.stdout }}'
          - 'locale_lang: {{ locale_lang }}'

    - name: Modify locale settings
      when: locale_lang != desired_locale
      block:

        - name: Enable locale '{{ desired_locale }}'
          become: true
          community.general.locale_gen:
            name: '{{ desired_locale }}'
            state: present

        - name: Configure locale to '{{ desired_locale }}'
          ansible.builtin.command:
            cmd: localectl set-locale LANG={{ desired_locale }}
