#!/usr/bin/env ansible-playbook
#
# Configure and trick-out default shell
---
- name: Remove unneeded pkgs
  hosts: all
  tasks:

    - name: Remove pkg conflicts for Powerline fonts
      become: true
      community.general.pacman:
        name:
          - powerline-fonts
        state: absent

- name: Install powerline fonts via `yay`
  vars:
    aur_packages:
      - spaceship-prompt-git  # terminal eye candy
      - powerline-fonts-git  # patched fonts for powerline
      - vim-plug  # vim plugin manager
    aur_packages_state: present
  ansible.builtin.import_playbook: function_yay.yml

- name: Configure baseline shell
  hosts: all
  tasks:

    - name: Install needed OS pkgs
      become: true
      community.general.pacman:
        name:
          - zsh  # shell
          - alacritty  # terminal
          - vim  # text editor
          - neovim  # upgraded text editor
          - ttf-jetbrains-mono  # font
          - powerline  # font
          - lynx  # terminal-based web browser
          - rsync  # (remote) file syncer
          - glxinfo  # GPU info
          - colordiff  # diff with color
          - borg  # encrypted, de-duplicated backups
          - transmission-cli  # torrent manager
          - nodejs  # dep for coc.nvim
          - galculator  # default calc
        state: present

    - name: Install needed pip3 pkgs
      ansible.builtin.pip:
        name:
          - psutil  # soft dep for powerline
          - i3ipc  # soft dep for powerline
          - powerline-status  # terminal beautification
          - neovim  # used by neovim

    - name: === zsh block ===
      block:

        - name: Ensure no .zshrc file exists
          ansible.builtin.file:
            path: ~/.zshrc
            state: absent

        - name: Add functionality for bashrc
          ansible.builtin.blockinfile:
            path: ~/.bashrc
            marker: "# {mark} shell_rc"
            block: "{{ lookup('file', 'files/shell_rc') }}"
            create: true
            mode: '0644'
            state: present

        - name: Add functionality for zshrc
          ansible.builtin.blockinfile:
            path: ~/.zshrc
            marker: "# {mark} shell_rc"
            block: "{{ lookup('file', '../files/shell_rc') }}"
            create: true
            mode: '0644'
            state: present

        - name: 'Set default shell to zsh for user: {{ ansible_user }}'
          become: true
          ansible.builtin.user:
            name: '{{ ansible_user }}'
            shell: /usr/bin/zsh

        - name: 'Set default shell to zsh for user: root'
          become: true
          ansible.builtin.user:
            name: root
            shell: /usr/bin/zsh

        - name: Copy custom .bashrc to user 'root'
          become: true
          ansible.builtin.copy:
            backup: true
            force: true
            remote_src: true
            src: '/home/{{ ansible_user }}/.bashrc'
            dest: /root/.bashrc
            owner: root
            group: root
            mode: '0644'

        - name: Copy custom .zshrc to user 'root'
          become: true
          ansible.builtin.copy:
            backup: true
            force: true
            remote_src: true
            src: '/home/{{ ansible_user }}/.zshrc'
            dest: /root/.zshrc
            owner: root
            group: root
            mode: '0644'

    - name: === i3 block ===
      block:

        - name: Ensure i3 is present
          become: true
          community.general.pacman:
            name:
              - i3-gaps
              - i3blocks
              - i3lock
              - i3status-manjaro
            state: present

        - name: Ensure i3 config dir is present
          ansible.builtin.file:
            path: ~/.i3/
            state: directory
            mode: '0755'

        - name: Copy default i3 file to `{{ ansible_user }}` profile
          ansible.builtin.copy:
            force: true
            src: files/i3_rc
            dest: ~/.i3/config
            mode: '0644'

    - name: === (neo)vim block ===
      block:

        - name: Ensure nvim directory exists
          ansible.builtin.file:
            path: ~/.config/nvim/
            state: directory
            mode: '0755'

        - name: Copy default nvim file to `{{ ansible_user }}` profile
          ansible.builtin.copy:
            remote_src: false
            force: true
            src: files/vim_rc
            dest: ~/.config/nvim/init.vim
            mode: '0644'

        - name: Install (neo)vim plugins
          ansible.builtin.command:
            cmd: nvim -c 'PlugUpdate | PlugUpgrade | PlugStatus | sleep 3 | q! | q!'
            creates: ~/.vim/plugged

    - name: === alacritty block ===
      block:

        - name: Set default font for terminal `alacritty`
          ansible.builtin.blockinfile:
            path: ~/.config/alacritty/alacritty.yml
            create: true
            state: present
            mode: '0644'
            block: |
              font:
                normal:
                  family: ProFont for Powerline
                  style: Regular
                size: 16
