#!/usr/bin/env ansible-playbook
#
# Download Dracula theme
#
# Reference: https://www.linuxfordevices.com/tutorials/linux/change-lightdm-theme-and-background
---
- name: Install Dracula theme
  hosts: all
  vars:
    dracula_filename: Dracula.tar.xz
  tasks:

    - name: Download Dracula theme
      ansible.builtin.get_url:
        url: 'https://github.com/dracula/gtk/releases/download/v3.0/{{ dracula_filename }}'
        checksum: sha256:d0a7af0baab7c2ec4ed138c7ee1e4558450154ee4b9a5545e7525d022a79d261
        dest: /tmp/
        mode: '0755'

    - name: Extract file
      become: true
      ansible.builtin.unarchive:
        remote_src: true
        src: '/tmp/{{ dracula_filename }}'
        dest: /usr/share/themes/

- name: Set theme to Dracula
  vars:
    selected_theme: Dracula
  ansible.builtin.import_playbook: dark_theme.yml
