#!/usr/bin/env ansible-playbook
#
# === Install AUR packages via yay ===
#
# Invoke like so (no indention nor inside of task block):
#
# - vars:
#     aur_packages:
#       - package1
#       - package2
#       ...
#     aur_packages_state: present|absent  # pick only one to install/uninstall
#   ansible.builtin.import_playbook: function_yay.yml
#
# NOTE:
# This playbook temporarily adds/removes a passwordless sudo ansible_user
# when using yay module since yay cannot be ran with sudo
# but will require (and prompt for sudoer password) later.
# This is a pretty egrious security hole, but the playbook is written such
# that it should always remove that hole after packages are installed, removed, or failed.
#
# Reference:
# https://github.com/kewlfft/ansible-aur#create-the-aur_builder-user
---
- name: '=== [FUNCTION_START] Add/Remove yay packages ==='
  hosts: all

  vars:
    - passwordless_sudo_user: '{{ ansible_user }}'
    - passwordless_sudo_file: /etc/sudoers.d/11-temp-passwordless-sudo-{{ passwordless_sudo_user }}
    - passwordless_sudo_program: /usr/bin/pacman
    - aur_packages: nop1,nop2,nop3
    - aur_packages_state: present

  tasks:

    - block:

        - name: Add `{{ passwordless_sudo_user }}` user to sudoers enabling passwordless `sudo pacman`
          become: true
          ansible.builtin.lineinfile:
            path: '{{ passwordless_sudo_file }}'
            line: '{{ passwordless_sudo_user }} ALL=(ALL) NOPASSWD: {{ passwordless_sudo_program }}'
            create: true
            validate: 'visudo -cf %s'
            mode: 0440
            state: present

        - name: Update yay's cache for AUR
          yay:
            update_cache: true

        - name: 'Ensure `yay` pkgs are: {{ aur_packages_state }}'
          yay:
            name:
              - '{{ item }}'
            state: '{{ aur_packages_state }}'
          loop: '{{ aur_packages }}'

      # Always removes this temp security hole even with a previous failure
      always:
        # Remove the `{{ passwordless_sudo_file }}` file
        - name: '=== [FUNCTION_END] REMOVE TEMP SUDOER FILE ==='
          become: true
          ansible.builtin.file:
            path: '{{ passwordless_sudo_file }}'
            state: absent
