#!/usr/bin/env ansible-playbook
#
# Add/remove temporary user when using yay module since
# yay cannot be ran as sudo but will require (and prompt for
# sudoer password) later.
#
# Reference:
# https://github.com/kewlfft/ansible-aur#create-the-aur_builder-user
---
- name: Add/Remove yay passwordless sudo user (to install AUR packages)
  hosts: all

  vars:
    - passwordless_sudo_user: '{{ ansible_user }}'
    - passwordless_sudo_file: /etc/sudoers.d/11-temp-passwordless-sudo-{{ passwordless_sudo_user }}
    - passwordless_sudo_program: /usr/bin/pacman
    - aur_packages: nop

  tasks:

    - name: Add `{{ passwordless_sudo_user }}` user to sudoers enabling passwordless `sudo pacman`
      become: true
      ansible.builtin.lineinfile:
        path: '{{ passwordless_sudo_file }}'
        line: '{{ passwordless_sudo_user }} ALL=(ALL) NOPASSWD: {{ passwordless_sudo_program }}'
        create: true
        validate: 'visudo -cf %s'
        mode: 0440
        state: present
      notify: UNINSTALL USER 

    - name: Install pkgs via `yay`
      yay:
        name:
          - '{{ item }}'
        state: present
      with_loop: aur_packages 

  handlers:
    # Remove the `{{ passwordless_sudo_file }}` file
    - name: UNINSTALL USER
      become: true
      ansible.builtin.file:
        path: '{{ passwordless_sudo_file }}'
        state: absent
