#!/usr/bin/env ansible-playbook
#
# Baseline packages and simple configurations
---
- name: Install (and remove) baseline packages from pacman, AUR, and PyPI
  hosts: all
  tasks:

  - name: Remove unwanted pkgs
    become: true
    community.general.pacman:
      name:
        - palemoon-bin
      state: absent

  - name: Remove unneeded files/dirs
    ansible.builtin.file:
      path: '{{ item }}'
      state: absent
    loop:
      - ~/.moonchild productions

  - name: Install pacman pkgs
    become: true
    community.general.pacman:
      # installation takes while so method will show "progress"
      name: '{{ item }}'
      update_cache: true
      state: present
    loop:
      - firefox  # web browser
      - calibre  # ereader (ebooks)
      - gedit  # text editor
      - flameshot  # screenshot
      - pkgfile  # pkg search from repos
      - strace  # debugger
      - bind-tools  # domain resolving
      - udisks2  # disk mounting
      - arandr  # desktop display configurator
      - base-devel  # meta package for compiling (e.g. AUR)
      - git  # repos
      - yay  # AUR installation
      - python  # Python3
      - python-pip  # pip package installer
      - numlockx  # numlock on at login
      - marker  # Markdown editor
      - libreoffice  # office suite of programs
      - unzip  # unzip

- name: Install AUR pkgs
  vars:
    aur_packages:
      - librewolf-bin  # security-focused web browser
      - optimus-manager  # GPU switcher
  ansible.builtin.import_playbook: function_yay.yml

- hosts: all
  tasks:

    - name: Miscellaneous config steps (that don't need their own playbooks)
      block:

        - name: Enable optimus-manager service
          become: true
          ansible.builtin.service:
            name: optimus-manager
            enabled: true
            state: started

        # https://wiki.archlinux.org/title/Activating_numlock_on_bootup
        - name: Copy numlockx systemd unitfile file to /etc/
          become: true
          ansible.builtin.copy:
            src: files/systemd/numlockx-on.service
            dest: /etc/systemd/system/
            owner: root
            group: root
            mode: '0644'

        - name: Enable numlockx-on service
          become: true
          ansible.builtin.service:
            name: numlockx-on
            enabled: true
            state: started

        - name: Tweak blur lock screen to blur more
          become: true
          ansible.builtin.lineinfile:
            backup: true
            backrefs: true
            path: /usr/bin/blurlock
            regexp: '(.*) -blur [0-9.]+x[0-9.]+ (.*)'
            line: '\1 -blur 0x100 \2'
            state: present
