#!/usr/bin/env ansible-playbook
#
# Add/remove temporary user when using yay module since
# yay cannot be ran as sudo but will require (and prompt for
# sudoer password) later.
#
# Reference:
# https://github.com/kewlfft/ansible-aur#create-the-aur_builder-user
---
- name: Add/Remove yay passwordless sudo user (to install AUR packages)
  hosts: all

  vars:
    - install_passwordless_sudo_user: false  # UNINSTALL by safe default
    - passwordless_sudo_user: aur_builder
    - passwordless_sudo_file: /etc/sudoers.d/11-install-{{ passwordless_sudo_user }}

  tasks:

    - name: True=INSTALL // False=UNINSTALL
      debug:
        msg: 'install_passwordless_sudo_user: {{ install_passwordless_sudo_user }}'

    - name: INSTALL USER
      when: install_passwordless_sudo_user is defined and install_passwordless_sudo_user | bool  # true
      block:
        - name: Create the `{{ passwordless_sudo_user }}` user
          become: true
          ansible.builtin.user:
            name: '{{ passwordless_sudo_user }}'
            create_home: false
            group: wheel
            state: present

        - name: Allow the `{{ passwordless_sudo_user }}` user to run `sudo pacman`
            without a password
          become: true
          ansible.builtin.lineinfile:
            path: '{{ passwordless_sudo_file }}'
            line: '{{ passwordless_sudo_user }} ALL=(ALL) NOPASSWD: ALL'
            create: true
            validate: 'visudo -cf %s'
            mode: 0440
            state: present

    - name: UNINSTALL USER
      when: install_passwordless_sudo_user is defined and not install_passwordless_sudo_user | bool  # false
      block:
        - name: Remove the `{{ passwordless_sudo_user }}` user
          become: true
          ansible.builtin.user:
            name: '{{ passwordless_sudo_user }}'
            remove: true
            state: absent

        - name: Remove the `{{ passwordless_sudo_file }}` file
          become: true
          ansible.builtin.file:
            path: '{{ passwordless_sudo_file }}'
            state: absent
