#!/usr/bin/env ansible-playbook
#
# Install nitrogen (wallpaper manager)
---
- name: Install and configure nitrogen wallpaper
  hosts: all
  tasks:

    - name: Install nitrogen pkg
      become: true
      community.general.pacman:
        name:
          - nitrogen
        state: present

    - name: Ensure wallpaper directory exists
      become: true
      ansible.builtin.file:
        path: /usr/share/backgrounds/1_PERSONAL_WALLPAPERS/
        state: directory
        mode: '0755'

    - name: Copy wallpaper to target
      become: true
      ansible.builtin.copy:
        force: true
        remote_src: false
        src: files/wallpapers/aoe2_italians.png
        dest: /usr/share/backgrounds/1_PERSONAL_WALLPAPERS/
        mode: '0755'

    - name: Copy nitrogen config to target
      ansible.builtin.copy:
        remote_src: false
        src: files/wallpapers/bg-saved.cfg
        dest: ~/.config/nitrogen/
        mode: '0755'
