#!/usr/bin/env ansible-playbook
#
# Install Vagrant (VM manager)
#
# Reference:
# https://wiki.archlinux.org/title/Vagrant#Installation
#
# sudo pacman vagrant
# sudo systemctl enable --now libvirtd
# vagrant plugin install vagrant-libvirt
# sudo usermod -aG libvirt $USER
---
- name: Install Vagrant
  hosts: all
  tasks:

  - name: Install needed OS pkgs
    become: true
    community.general.pacman:
      name:
        - vagrant
        - libvirt
        - qemu
        - nfs-utils
      update_cache: true
      state: present

  - name: Enable libvirtd service
    become: true
    ansible.builtin.service:
      name: libvirtd
      enabled: true
      state: started

  # !!! ADD nfs.conf modification here !!!

    # https://wiki.archlinux.org/title/Vagrant#Mounting_NFS_shared_folders:_mount.nfs:_requested_NFS_version_or_transport_protocol_is_not_supported 
  - name: Enable nfs-server service
    become: true
    ansible.builtin.service:
      name: nfs-server
      enabled: true
      state: restarted

  - name: Check if libvirt plugin is installed
    ansible.builtin.command:
      cmd: vagrant plugin list
    register: output_vagrant_plugin_list
    changed_when: output_vagrant_plugin_list.rc != 0

  - name: Show Vagrant plugin list
    ansible.builtin.debug:
      msg:
        - "=== vagrant plugin list output ==="
        - "{{ output_vagrant_plugin_list }}"

  - name: Install libvirt plugin for Vagrant, if absent
    ansible.builtin.command:
      cmd: vagrant plugin install vagrant-libvirt
    when: output_vagrant_plugin_list.stdout is not regex(".*vagrant-libvirt.*")

  - name: Add '{{ ansible_user }}' to libvirt group
    become: true
    ansible.builtin.user:
      name: '{{ ansible_user }}'
      group: libvirt
      state: present
