#!/usr/bin/env ansible-playbook
#
# This playbook will ensure the whole KeepassXC setup is installed
# Reference:
# https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration
---
    - name: Install browser
      become: true
      ansible.builtin.package:
        name:
          - firefox  # web browser
        state: present

    - name: Install KeepassXC password manager and required packages
      become: true
      ansible.builtin.package:
        name:
          - keepassxc
        state: present

    - name: Browser config to allow keepassxc-browser extension to communicate
      ansible.builtin.copy:
        remote_src: false
        src: files/browser/native-messaging-hosts
        dest: ~/.mozilla/
        mode: '0770'

    # NOTE: not necessary?: https://archlinux.org/packages/community/x86_64/keepassxc/
    #    - name: Copy keepassxc-proxy binary into /usr/bin/
    #      become: true
    #      ansible.builtin.copy:
    #        remote_src: false
    #        src: files/browser/native-messaging-hosts/keepassxc-proxy
    #        dest: /usr/bin/keepassxc-proxy
    #        owner: root
    #        group: root
    #        mode: '0755'

    - name: Copy keepassxc-proxy systemd unitfile file to /etc/
      become: true
      ansible.builtin.copy:
        remote_src: false
        src: files/systemd/keepassxc-proxy.service
        dest: /etc/systemd/system/
        owner: root
        group: root
        mode: '0644'

    - name: Enable keepassxc-proxy service
      become: true
      ansible.builtin.service:
        name: keepassxc-proxy
        enabled: true
        state: started

    - name: Set KeepassXC theme to system (classic)
      ansible.builtin.blockinfile:
        path: ~/.config/keepassxc/keepassxc.ini
        marker: '# {mark} keepassxc_theme'
        block: |
          [GUI]
          ApplicationTheme=classic
        mode: '0644'
        create: true
        state: present
