#!/usr/bin/env ansible-playbook
---
- hosts: all
  tasks:
    - name: Target OS
      ansible.builtin.debug:
        msg: 'TARGET OS: {{ ansible_facts["distribution"] }}'

# === ARCH LINUX ===

# Arch: https://archlinux.org/packages/ | https://aur.archlinux.org/
- ansible.builtin.import_playbook: baseline_arch.yml
  when: ansible_facts["distribution"] == "Archlinux"

- ansible.builtin.import_playbook: arch_general_recommendations.yml
  when: ansible_facts["distribution"] == "Archlinux"

# === KALI LINUX ===

# Kali: https://pkg.kali.org
- ansible.builtin.import_playbook: baseline_kali.yml
  when: ansible_facts["distribution"] == "Kali"

- ansible.builtin.import_playbook: i3.yml
- ansible.builtin.import_playbook: dark_theme.yml
- ansible.builtin.import_playbook: conky.yml
- ansible.builtin.import_playbook: nitrogen.yml
- ansible.builtin.import_playbook: keepassxc.yml
- ansible.builtin.import_playbook: shell.yml
- ansible.builtin.import_playbook: spanish_locale.yml
- ansible.builtin.import_playbook: docker.yml
- ansible.builtin.import_playbook: grub.yml
- ansible.builtin.import_playbook: calibre.yml
- ansible.builtin.import_playbook: virtualization.yml
- ansible.builtin.import_playbook: vagrant.yml
# NOTE: steam must be at the end since it upgrades the system,
# which breaks some other things until a reboot is completed
- ansible.builtin.import_playbook: steam.yml
