#!/usr/bin/env ansible-playbook
---
- ansible.builtin.import_playbook: arch_baseline.yml
- ansible.builtin.import_playbook: arch_general_recommendations.yml
- ansible.builtin.import_playbook: i3.yml
- ansible.builtin.import_playbook: nitrogen.yml
- ansible.builtin.import_playbook: shell.yml
- ansible.builtin.import_playbook: spanish_locale.yml
- ansible.builtin.import_playbook: docker.yml
- ansible.builtin.import_playbook: grub.yml
- ansible.builtin.import_playbook: calibre.yml
- ansible.builtin.import_playbook: keepassxc.yml
  #- ansible.builtin.import_playbook: steam.yml
- ansible.builtin.import_playbook: virtualization.yml
