#!/usr/bin/env ansible-playbook
#
# Configure and trick-out default shell
---
- name: Remove unneeded pkgs
  hosts: all
  tasks:

- name: Install necessary AUR packages
  vars:
    aur_packages:
      - spaceship-prompt  # terminal eye candy
      - powerline-fonts-git  # patched fonts for powerline
      - vim-plug  # vim plugin manager
      - inxi  # more systeminfo
    aur_packages_state: present
  ansible.builtin.import_playbook: function_yay.yml

- name: Configure baseline shell
  hosts: all
  vars:
    default_browser_name: firefox
    default_browser_fullpath: '/usr/bin/{{ default_browser_name }}'
    default_image_viewer: deepin-image-viewer
  tasks:

    - name: Install needed OS pkgs
      become: true
      ansible.builtin.package:
        name:
          # - python  # the legend
          # - python-pip  # install pkgs from PyPI
          # - python-setuptools  # build packages
          # - python-pynvim  # python3 for neovim
          - zsh  # shell
          - zsh-completions  # zsh command completions
          - zsh-syntax-highlighting  # zsh syntax highlighting
          - zsh-autosuggestions  # finish commands from history
          - zsh-history-substring-search  # autosearch via history
          - grml-zsh-config  # zsh config used in archiso (liveboot ISO)
          - pkgfile  # command not found trick
          - zoxide  # smarter cd
          - fzf  # fuzzy finder
          - ripgrep  # fast, recursive grep searcher
          - fd  # faster `find` command
          - alacritty  # terminal
          - vim  # text editor
          - neovim  # upgraded text editor
          - ttf-jetbrains-mono-nerd  # font
          - powerline  # font
          - rsync  # (remote) file syncer
          - glxinfo  # GPU info
          - colordiff  # diff with color
          - borg  # encrypted, de-duplicated backups
          - python-llfuse  # dep for borg backup
          - transmission-cli  # torrent manager
          - transmission-gtk  # GUI torrent manager client
          - transmission-remote-gtk  # GUI torrent manager daemon
          - nodejs  # dep for coc.nvim
          - xclip  # dep for vim clipboard
          - galculator  # default calc
          - geckodriver  # used by Selenium for Firefox browsers
          - screenfetch  # display system info
          - socat  # dep for powerline
          - xorg-xrandr  # dep for powerline
          - ansible-lint  # linter for Ansible
          # - texlive-most  # LaTeX generator dep for vim-latex-live-preview
          - deepin-image-viewer  # simple image viewer
        state: present

    # https://wiki.archlinux.org/title/Powerline
    # https://powerline.readthedocs.io/en/master/installation.html
    #    - name: Install needed pip3 pkgs
    #      ansible.builtin.pip:
    #        extra_args: --break-system-packages
    #        name:
    #          - psutil  # soft dep for powerline
    #          - pygit2  # soft dep for powerline
    #          - i3ipc  # soft dep for powerline
    #          - powerline-status  # terminal beautification
    #          - neovim  # used by neovim

    - name: === zsh block ===
      block:

        - name: Add functionality for shells
          ansible.builtin.blockinfile:
            path: '/home/{{ ansible_user }}/{{ item }}'
            marker: "# {mark} zsh_rc"
            block: "{{ lookup('file', '../files/zsh_rc') }}"
            create: true
            owner: '{{ ansible_user }}'
            group: '{{ ansible_user }}'
            mode: '0644'
            state: present
          loop:
            - .zshrc
            # - .bashrc

            mode: '0644'
            state: present
          loop:
            - .zshrc
            # - .bashrc

        - name: Copy custom zsh_rc to root
          become: true
          ansible.builtin.copy:
            backup: true
            remote_src: true
            src: '/home/{{ ansible_user }}/{{ item }}'
            dest: '/root/{{ item }}'
            owner: root
            group: root
            mode: '0644'
          loop:
            - .zshrc
            # - .bashrc

        - name: 'Set default shell to zsh for users root and {{ ansible_user }}'
          become: true
          ansible.builtin.user:
            name: '{{ item }}'
            shell: /usr/bin/zsh
          loop:
            - '{{ ansible_user }}'
            - root

        - name: Build pkgfile cache (first time only)
          become: true
          ansible.builtin.command:
            cmd: pkgfile --update
            creates: /var/cache/pkgfile/core.files

    - name: === Spaceship prompt block ===
      block:
        - name: Copy spaceship config
          ansible.builtin.copy:
            remote_src: false
            src: files/spaceship_rc
            dest: ~/.spaceshiprc.zsh
            force: true
            mode: '0644'

    - name: === neovim / NvChad block ===
      block:

        - name: Ensure nvim directory exists
          ansible.builtin.file:
            path: ~/.config/nvim/
            state: directory
            mode: '0755'

        # https://nvchad.com/docs/quickstart/install#install
        - name: 'Clone nvChad to profile: {{ ansible_user }}'
          ansible.builtin.git:
            repo: https://github.com/NvChad/starter
            dest: ~/.config/nvim

            # - name: Check if the plugins folder is empty
            #   changed_when: false
            #   ansible.builtin.find:
            #     file_type: any
            #     paths: ~/.local/share/nvim/
            #   register: plugin_files

        # Will likely fail if plugins not installed yet
        - name: Install plugins
          ignore_errors: true
          # when: plugin_files.matched <= 0
          ansible.builtin.command:
            cmd: nvim --headless '+MasonInstallAll' '+qa'

    - name: === alacritty block ===
      block:

        - name: Ensure alacritty directory exists
          ansible.builtin.file:
            path: ~/.config/alacritty/
            state: directory
            mode: '0755'

        - name: Set default font for terminal `alacritty`
          ansible.builtin.copy:
            force: true
            src: files/alacritty.toml
            dest: ~/.config/alacritty/alacritty.toml
            mode: '0644'

    - name: === /etc/environment block ===
      block:

        - name: Template /etc/environment
          become: true
          ansible.builtin.blockinfile:
            path: /etc/environment
            marker: '# {mark} environment_config'
            block: |
              EDITOR=/usr/bin/nvim
              BROWSER={{ default_browser_fullpath }}
              TERMINAL=/usr/bin/alacritty
            create: true
            state: present
            mode: '0644'
            owner: root
            group: root

    - name: === mimeapps.list block ===
      vars:
        mimeapps_file: ~/.config/mimeapps.list
      block:

        # https://stackoverflow.com/a/64850938
        - name: 'Template {{ mimeapps_file }}'
          ansible.builtin.blockinfile:
            path: '{{ mimeapps_file }}'
            marker: '# {mark} mimeapps_list_config'
            block: |
              [Default Applications]
              text/html={{ default_browser_name }}.desktop
              x-scheme-handler/http={{ default_browser_name }}.desktop
              x-scheme-handler/https={{ default_browser_name }}.desktop
              x-scheme-handler/ftp={{ default_browser_name }}.desktop
              x-scheme-handler/chrome={{ default_browser_name }}.desktop
              application/x-extension-htm={{ default_browser_name }}.desktop
              application/x-extension-html={{ default_browser_name }}.desktop
              application/x-extension-shtml={{ default_browser_name }}.desktop
              application/xhtml+xml={{ default_browser_name }}.desktop
              application/x-extension-xhtml={{ default_browser_name }}.desktop
              application/x-extension-xht={{ default_browser_name }}.desktop
              image/jpeg={{ default_image_viewer }}.desktop
              image/png={{ default_image_viewer }}.desktop
            create: true
            state: present
            mode: '0644'
