#!/usr/bin/env ansible-playbook
#
# Configure and trick-out default shell
---
- name: Remove unneeded pkgs
  hosts: all
  tasks:

    - name: Remove pkg conflicts for Powerline fonts
      become: true
      community.general.pacman:
        name:
          - powerline-fonts
        state: absent

- name: Install necessary AUR packages
  vars:
    aur_packages:
      - spaceship-prompt-git  # terminal eye candy
      - powerline-fonts-git  # patched fonts for powerline
      - vim-plug  # vim plugin manager
      - inxi  # more systeminfo
    aur_packages_state: present
  ansible.builtin.import_playbook: function_yay.yml

- name: Configure baseline shell
  hosts: all
  vars:
    - default_browser: /usr/bin/librewolf
  tasks:

    - name: Install needed OS pkgs
      become: true
      community.general.pacman:
        name:
          - zsh  # shell
          - alacritty  # terminal
          - vim  # text editor
          - neovim  # upgraded text editor
          - ttf-jetbrains-mono  # font
          - powerline  # font
          - lynx  # terminal-based web browser
          - rsync  # (remote) file syncer
          - glxinfo  # GPU info
          - colordiff  # diff with color
          - borg  # encrypted, de-duplicated backups
          - transmission-cli  # torrent manager
          - transmission-gtk  # GUI torrent manager client
          - transmission-remote-gtk  # GUI torrent manager daemon
          - nodejs  # dep for coc.nvim
          - xclip  # dep for vim clipboard
          - galculator  # default calc
          - geckodriver  # used by Selenium for Firefox browsers
          - texlive-most  # LaTeX generator dep for vim-latex-live-preview
          - screenfetch  # display system info
        state: present

    - name: Install needed pip3 pkgs
      ansible.builtin.pip:
        name:
          - psutil  # soft dep for powerline
          - i3ipc  # soft dep for powerline
          - powerline-status  # terminal beautification
          - neovim  # used by neovim
          - selenium  # Website automation
          - requests  # HTTP actions

    - name: === zsh block ===
      block:

        # I don't like the Manjaro defaults at all
        - name: Ensure no .zshrc file exists
          ansible.builtin.file:
            path: ~/.zshrc
            state: absent

        - name: Overwrite current shell_rc with skeleton, original version
          become: true
          ansible.builtin.copy:
            backup: true
            force: true
            remote_src: true
            src: '/etc/skel/{{ item }}'
            dest: '~/{{ item }}'
            owner: '{{ ansible_user }}'
            group: '{{ ansible_user }}'
            mode: '0644'
          loop:
            - .bashrc

        - name: Add functionality for shells
          ansible.builtin.blockinfile:
            path: '~/{{ item }}'
            marker: "# {mark} shell_rc"
            block: "{{ lookup('file', '../files/shell_rc') }}"
            create: true
            mode: '0644'
            state: present
          loop:
            - .zshrc
            - .bashrc

        - name: Copy custom shell_rc to root
          become: true
          ansible.builtin.copy:
            backup: true
            force: true
            remote_src: true
            src: '/home/{{ ansible_user }}/{{ item }}'
            dest: '/root/{{ item }}'
            owner: root
            group: root
            mode: '0644'
          loop:
            - .zshrc
            - .bashrc

        - name: Set default shell to zsh for user "{{ ansible_user }}" and root
          become: true
          ansible.builtin.user:
            name: '{{ item }}'
            shell: /usr/bin/zsh
          loop:
            - '{{ ansible_user }}'
            - root

    - name: === i3 block ===
      block:

        - name: Ensure i3 is present
          become: true
          community.general.pacman:
            name:
              - i3-gaps
              - i3blocks
              - i3lock
            state: present

        - name: Ensure i3 config dir is present
          ansible.builtin.file:
            path: ~/.config/i3/
            state: directory
            mode: '0755'

        - name: Copy default i3 file to `{{ ansible_user }}` profile
          ansible.builtin.copy:
            force: true
            src: files/i3_rc
            dest: ~/.config/i3/config
            mode: '0644'

    - name: === (neo)vim block ===
      block:

        - name: Ensure nvim directory exists
          ansible.builtin.file:
            path: ~/.config/nvim/
            state: directory
            mode: '0755'

        - name: Copy default nvim file to `{{ ansible_user }}` profile
          ansible.builtin.copy:
            remote_src: false
            src: files/vim_rc
            dest: ~/.config/nvim/init.vim
            force: true
            mode: '0644'

        - name: Download/Install (neo)vim plugins
          changed_when: true
          ansible.builtin.command:
            cmd: nvim -c 'PlugUpdate | PlugUpgrade | UpdateRemotePlugins | PlugStatus | sleep 3 | q! | q!'

    - name: === alacritty block ===
      block:

        - name: Set default font for terminal `alacritty`
          ansible.builtin.blockinfile:
            path: ~/.config/alacritty/alacritty.yml
            create: true
            state: present
            mode: '0644'
            block: |
              font:
                normal:
                  family: ProFont for Powerline
                  style: Regular
                size: 16

    - name: === .profile block ===
      block:

        - name: Template ~/.profile
          ansible.builtin.blockinfile:
            path: ~/.profile
            create: true
            state: present
            mode: '0644'
            block: |
              export EDITOR=/usr/bin/nvim
              export BROWSER={{ default_browser }}
              export TERMINAL=/usr/bin/alacritty

    - name: === mimeapps.list block ===
      vars:
        mimeapps_file: ~/.config/mimeapps.list
      block:

        - name: 'Template {{ mimeapps_file }}'
          ansible.builtin.blockinfile:
            path: '{{ mimeapps_file }}'
            create: true
            state: present
            mode: '0644'
            block: |
              [Default Applications]
              text/html={{ default_browser }}
              x-scheme-handler/http={{ default_browser }}
              x-scheme-handler/https={{ default_browser }}
              x-scheme-handler/ftp={{ default_browser }}
              x-scheme-handler/chrome={{ default_browser }}
              application/x-extension-htm={{ default_browser }}
              application/x-extension-html={{ default_browser }}
              application/x-extension-shtml={{ default_browser }}
              application/xhtml+xml={{ default_browser }}
              application/x-extension-xhtml={{ default_browser }}
              application/x-extension-xht={{ default_browser }}
              image/jpeg={{ default_browser }}
              image/png={{ default_browser }}
