#!/usr/bin/env ansible-playbook
#
# Setup virtualization
---
- name: Install baseline pkgs
  hosts: all
  vars:
    vbox: true
    # qemu: true
  tasks:

    # https://wiki.archlinux.org/title/VirtualBox
    - name: === Virtualbox ===
      when: vbox|bool
      block:

        - name: Install virtualbox pkgs
          become: true
          community.general.pacman:
            name:
              - virtualbox
              - virtualbox-host-modules-arch
            state: present

    # https://wiki.archlinux.org/title/QEMU
    - name: === QEMU ===
      when: qemu|bool
      block:

        - name: Install qemu pkgs
          become: true
          community.general.pacman:
            name:
              - qemu-full
            state: present

    # https://wiki.archlinux.org/index.php/VirtualBox/Install_Arch_Linux_as_a_guest
    - name: Check for Virtualbox virtualization (VM running inside of vbox)
      become: true
      changed_when: false
      ignore_errors: true
      ansible.builtin.shell:
        cmd: dmidecode | grep --ignore-case --quiet --extended-regexp 'virtualbox|vbox'
      register: is_virtualbox

    - name: Virtualbox-specific actions
      when: is_virtualbox.rc == 0
      block:

        - name: Install Virtualbox Guest and NFS customizations
          become: true
          ansible.builtin.pacman:
            name:
              - virtualbox-guest-utils
              - nfs-utils
            state: present

        - name: Enable Guest Additions and NFS services
          become: true
          ansible.builtin.service:
            name: '{{ item }}'
            state: started
            enabled: true
          loop:
            - vboxservice
            - rpcbind

        - name: Add `{{ ansible_user }}` to docker group
          become: true
          ansible.builtin.user:
            name: '{{ ansible_user }}'
            groups: vboxsf
            append: true
            state: present
