#!/usr/bin/env ansible-playbook
#
# This playbook will ensure the whole KeepassXC setup is installed
# Reference:
# https://keepassxc.org/docs/KeePassXC_GettingStarted.html#_setup_browser_integration
---
- name: KeepassXC, keepassxc-browser, keepassxc-proxy
  hosts: all
  tasks:

  - name: Install KeepassXC password manager and required packages
    become: true
    # https://docs.ansible.com/ansible/latest/collections/community/general/pacman_module.html
    community.general.pacman:
      name:
        - keepassxc
      state: present

- name: Create temp user for yay invocation
  vars:
    install_passwordless_sudo_user: true
    passwordless_sudo_user: '{{ ansible_user }}'
  ansible.builtin.import_playbook: install_yay_passwordless_sudo_user.yml

- hosts: all
  tasks:
  - name: Install Librewolf package
    # https://github.com/mnussbaum/ansible-yay
    yay:
      name: 
        - librewolf-bin
          # TODO: enable service
        - optimus-manager
      state: present

- name: Delete temp user for yay invocation
  vars:
    install_passwordless_sudo_user: false
    passwordless_sudo_user: '{{ ansible_user }}'
  ansible.builtin.import_playbook: install_yay_passwordless_sudo_user.yml

- hosts: all
  tasks:
  - name: Browser config to allow keepassxc-browser extension to communicate
    ansible.builtin.copy:
      src: files/browser/native-messaging-hosts
      dest: ~/.librewolf/

  - name: Copy keepassxc-proxy binary into /usr/bin/
    become: true
    ansible.builtin.copy:
      remote_src: false
      src: files/keepassxc-proxy
      dest: /usr/bin/keepassxc-proxy
      owner: root
      group: root
      mode: '0755'

  - name: Copy keepassxc-proxy systemd unitfile file to /etc/
    become: true
    ansible.builtin.copy:
      src: files/systemd/keepassxc-proxy.service
      dest: /etc/systemd/system/
      owner: root
      group: root
      mode: '0644'

  - name: Enable keepassxc-proxy service
    become: true
    ansible.builtin.service:
      name: keepassxc-proxy
      enabled: true
      state: started

  - name: Enable optimus-manager service
    become: true
    ansible.builtin.service:
      name: optimus-manager
      enabled: true
      state: started

